version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: instalink_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    command: bash -c "bin/rails db:create db:migrate && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://developer:developer@db:5432/instalink_development
      RAILS_ENV: development
    user: "1000:1000"


volumes:
  db_data:
